version: '3.8'

services:
  bot:
    #image: bot_image:latest
    build:
      context: .
      dockerfile: bot/Dockerfile.bot
    depends_on:
      - db
    environment:
    
      - DATABASE_URL=postgres://postgres:1234@db:5432/ptdev
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      my_custom_network:
        ipv4_address: 172.20.0.3

  db:
    #image: db_image:latest
    build:
      context: .
      dockerfile: db/Dockerfile.db
    environment:
    
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - /home/larkined/tgbot/postgresql:/var/lib/postgresql/data
      
     
    networks:
      my_custom_network:
        ipv4_address: 172.20.0.2
    ports:
      - "5432:5432"
      - "2222:22"  # Открываем порт для SSH
  
  db_replica:
    #image: db_repl_image:latest
    build:
      context: .
      dockerfile: db_repl/Dockerfile.replica
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - db_replica_data:/var/lib/postgresql/data

    networks:
      my_custom_network:
        ipv4_address: 172.20.0.4

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db_data:
  db_replica_data:
