# Используем официальный образ PostgreSQL 15.1
FROM postgres:15.1

# Устанавливаем переменные окружения для базы данных
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=postgres

# Копируем SQL-скрипт для инициализации базы данных
COPY db/init.sql /docker-entrypoint-initdb.d/




RUN apt-get update && apt-get install -y openssh-server && apt install nano && apt install sudo

RUN useradd -ms /bin/bash lar
RUN echo "lar:1234" | chpasswd

RUN echo "postgres:1234" | chpasswd

RUN mkdir /var/run/sshd
RUN echo 'lar ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN sed -i 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config



# Устанавливаем права на выполнение для скрипта инициализации
RUN chmod +x /docker-entrypoint-initdb.d/init.sql

# Команда для запуска PostgreSQL

CMD service ssh start && docker-entrypoint.sh postgres