# pg_hba.conf

# Локальные подключения
local   all             all                                     md5

# Подключения по IPv4
host    all             all             0.0.0.0/0                md5

# Подключения по IPv6
host    all             all             ::/0                     md5
