# Используем официальный образ PostgreSQL 15.1
FROM postgres:15.1

# Устанавливаем переменные окружения для базы данных
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=postgres

RUN apt-get update && apt-get install -y openssh-server && apt install nano

RUN pg_createcluster 15 main --start


# Копируем конdockeфигурационные файлы для репликации

# Устанавливаем права на конфигурационные файлы


RUN rm -r /var/lib/postgresql/15/main/*

# Команда для запуска PostgreSQL
CMD docker-entrypoint.sh postgres